### ISSUE TITLE
Problème constaté lors de l'atelier du 14 janvier

### ISSUE THREAD

**Issue by MartinDelille** [BleepSound/ms20-vcf-simple#2]
- [x] Manque un détrompeur sur le CMS

**Comment by arthursaunier** [comment]
Alors en fait il y en a un. Sur la serigraphie, tu as un cote avec une barre longue qui specifie la pin 1. Mais je peux ajouter un truc en plus pour que ce soit plus visible.

**Comment by arthursaunier** [comment]
J'ai rajoute une marque suplementaire du coup.
