### ISSUE TITLE
Création du module sur modulargrid

### ISSUE THREAD

**Issue by MartinDelille** [BleepSound/ms20-vcf-simple#3]
Je voulais créer le module sur https://www.modulargrid.net/ et j'ai besoin de ces infos:

<img width="769" alt="Screenshot 2023-01-15 at 12 39 55" src="https://user-images.githubusercontent.com/879889/212538457-7eb12101-08bb-4709-9225-59d41d7a23b9.png">

**Comment by arthursaunier** [comment]
Jamais fait de mesure, il faudrait que je fasse ca.

**Comment by arthursaunier** [comment]
Module créé 
https://www.modulargrid.net/e/other-unknown-bleepsound-ms20-vcf

**Comment by MartinDelille** [comment]
Il faudrait le rajouter au readme à l'occase.
